---
# see helm configuration in
# https://www.consul.io/docs/k8s/helm#ui
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: consul
spec:
  releaseName: consul
  chart:
    spec:
      chart: consul
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "0.43.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://artifacthub.io/packages/helm/hashicorp/consul?modal=values
  # https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
  values:
    gossipEncryption:
      secretName: "gossipenc"
      secretKey: "cb98bfa0"
    tls:
      enabled: true
      enableAutoEncrypt: true
    server:
      enabled: true
      image: null
      replicas: 3
      bootstrapExpect: 3  # Should <= replicas count
    client:
      enabled: true
      image: null
      join: null
    ui:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: consul.staging
            paths:
              - /ui
        annotations: |
          'kubernetes.io/ingress.class': nginx
    tests:
      enabled: true
